# Configuration for https://cirrus-ci.org/

env:
  GOPROXY: https://proxy.golang.org

# Run go tests under a FreeBSD VM.
# Note that by default it is run as root, which causes the tests to fail since
# they expect to get permission denied on some cases, so we create a separate
# user and use that instead.
freebsd_task:
  name: Go tests (FreeBSD)
  freebsd_instance:
      image_family: freebsd-13-0-snap
  install_script: |
    pkg install -y lang/go
    pw useradd testing -m
  test_script: |
    su testing -c "go test ./..."
